package com.keystone.kms.domain

/** Representative of all operations that can be performed on a KMS key.
  * Each operation is associated with a specific action that can be performed
  * through Crypto Service Provider's (CSP) API. This allows the enforcement of approved transactions at the
  * type level, ensuring only explicitly authorized services can invoke a given cryptographic operation 
  * through CSP.
  * 
  * Restriction: Each operation is designed to be mutually exclusive. For example, a service that has been 
  * granted Encrypt permission cannot perform Decrypt operations, unless explicitly granted through the 
  * Decrypt operation. This allows for fine-grained access control and minimizes the blast radius of 
  * potential key misuse. 
  */
sealed trait KeyOperation

object KeyOperation: 
    /** This operation grants an entity the ability to encrypt data using a KMS key. This operation
      * is intended for services to encrypt data, using the KMS key using CSP. 
      */
    case object Encrypt extends KeyOperation

    /** This operation grants an entity the ability to decrypt data that was encrypted using a KMS key.
      * This operation is intended for use to decrypt data that was encrypted using a KMS key using CSP.
      */
    case object Decrypt extends KeyOperation

    /** This operation grants an entity the ability to wrap (encrypt) a data encryption key (DEK) using its
      * associated key encryption key (KEK). This operation is intended for use when a service needs to encrypt
      * a DEK for storage, ensuring that the DEK can only be decrypted by a service with the appropriate permissions
      * to do so. This is a critical operation for secure key management and ensures that DEKs are protected at rest.
      */
    case object Wrap extends KeyOperation

    /** This operation grants an entity the ability to unwrap (decrypt) a data encryption key (DEK) that was
      * previously wrapped using the Wrap operation. This operation is intended for use when a service needs to
      * retrieve the plaintext DEK for cryptographic operations, ensuring that only services with explicit permissions
      * can access the plaintext DEK. This is a critical operation for secure key management and ensures that DEKs are
      * only accessible to authorized services.
      */
    case object Unwrap extends KeyOperation

    /** This operation grants an entity the ability to perform digital signing operations using an assigned KMS key.
      * This operation is intended for use when a service needs to generate a digital signature for data integrity
      * verification purposes, ensuring that data transmitted can be verified for authenticity and integrity. This
      * operation is critical for ensuring that data has not been tampered with and can be trusted by recipients.
      */
    case object Sign extends KeyOperation

    /** This operation grants an entity the ability to perform digital signature verification using an assigned KMS key.
      * This operation is intended for use when a service needs to verify a digital signature generated by the Sign operation,
      * ensuring that data received can be verified for authenticity and integrity. This operation is critical for ensuring that
      * data has not been tampered with and can be trusted by recipients.
      */
    case object Verify extends KeyOperation
